package com.metacraft.api.modules.ai.service;

import ai.z.openapi.service.model.ChatMessageRole;
import com.metacraft.api.modules.ai.dto.AgentRequestDTO;
import com.metacraft.api.modules.ai.entity.ChatMessageEntity;
import com.metacraft.api.modules.ai.entity.ChatSessionEntity;
import com.metacraft.api.modules.ai.repository.ChatMessageRepository;
import com.metacraft.api.modules.ai.repository.ChatSessionRepository;
import com.metacraft.api.modules.app.entity.AppEntity;
import com.metacraft.api.modules.app.entity.AppVersionEntity;
import com.metacraft.api.modules.app.service.AppService;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import com.metacraft.api.modules.ai.dto.AppMetadataDTO;
import java.util.concurrent.CompletableFuture;

@Slf4j
@Service
@RequiredArgsConstructor
public class AgentMessageService {

    private final ChatMessageRepository chatMessageRepository;
    private final ChatSessionRepository chatSessionRepository;
    private final AppService appService;

    @Transactional
    public String initSessionAndSaveUserMessage(AgentRequestDTO request, Long userId) {
        String sessionId = request.getSessionId();
        if (sessionId == null || sessionId.isEmpty()) {
            sessionId = java.util.UUID.randomUUID().toString();
            
            // 创建新会话
            String title = request.getMessage().length() > 20 ? request.getMessage().substring(0, 20) + "..." : request.getMessage();
            ChatSessionEntity sessionEntity = ChatSessionEntity.builder()
                    .userId(userId)
                    .sessionId(sessionId)
                    .title(title)
                    .build();
            chatSessionRepository.save(sessionEntity);
        }

        // 保存用户消息
        ChatMessageEntity userEntity = ChatMessageEntity.builder()
                .userId(userId)
                .sessionId(sessionId)
                .role(ChatMessageRole.USER.value())
                .content(request.getMessage())
                .build();
        chatMessageRepository.save(userEntity);
        return sessionId;
    }

    public void saveAssistantMessage(Long userId, String sessionId, String content) {
        saveAssistantMessage(userId, sessionId, content, null, null);
    }

    public void saveAssistantMessage(Long userId, String sessionId, String content, Long relatedAppId, Long relatedVersionId) {
        ChatMessageEntity botEntity = ChatMessageEntity.builder()
                .userId(userId)
                .sessionId(sessionId)
                .role(ChatMessageRole.ASSISTANT.value())
                .content(content)
                .relatedAppId(relatedAppId)
                .relatedVersionId(relatedVersionId)
                .type(relatedAppId != null ? "app" : "text")
                .build();
        chatMessageRepository.save(botEntity);
    }

    @Transactional
    public AppVersionEntity handleGenCompletion(Long userId, String sessionId, String userPrompt, String fullContent, CompletableFuture<AppMetadataDTO> metadataFuture) {
        // Clean up markdown code blocks
        String cleanContent = fullContent.trim();
        
        // Safety check: Remove delimiter if it exists (in case AgentService missed it or passed raw content)
        String DELIMITER = "<<<<CODE_GENERATION>>>>";
        int delimiterIndex = cleanContent.lastIndexOf(DELIMITER);
        if (delimiterIndex != -1) {
            cleanContent = cleanContent.substring(delimiterIndex + DELIMITER.length()).trim();
        }

        if (cleanContent.startsWith("```html")) {
            cleanContent = cleanContent.substring(7);
        } else if (cleanContent.startsWith("```")) {
            cleanContent = cleanContent.substring(3);
        }
        
        cleanContent = cleanContent.trim();
        
        if (cleanContent.endsWith("```")) {
            cleanContent = cleanContent.substring(0, cleanContent.length() - 3);
        }
        cleanContent = cleanContent.trim();

        // 1. Get ChatSession
        ChatSessionEntity session = chatSessionRepository.findBySessionId(sessionId).orElse(null);
        if (session == null) {
            log.warn("Session not found for completion: {}", sessionId);
            saveAssistantMessage(userId, sessionId, cleanContent);
            return null;
        }

        Long appId = session.getRelatedAppId();

        // 2. If no appId, create new App
        if (appId == null) {
            String appName = userPrompt.length() > 20 ? userPrompt.substring(0, 20) : userPrompt;
            AppEntity newApp = appService.createApp(userId, appName, "Generated by AI");
            appId = newApp.getId();

            // Update session
            session.setRelatedAppId(appId);
            chatSessionRepository.save(session);
        }

        // Apply metadata if available (async update)
        if (metadataFuture != null) {
            final Long finalAppId = appId;
            metadataFuture.thenAccept(metadata -> {
                if (metadata != null) {
                    appService.updateAppMetadata(finalAppId, metadata.getName(), metadata.getDescription());
                }
            }).exceptionally(e -> {
                log.error("Failed to update app metadata for app {}", finalAppId, e);
                return null;
            });
        }

        // 3. Create Version
        AppVersionEntity version = appService.createVersion(appId, cleanContent, userPrompt);

        // 4. Save Message with relation (content is null for app generation)
        saveAssistantMessage(userId, sessionId, null, appId, version.getId());
        
        return version;
    }
}
